[package]
name = "erlls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.19"
orfail = "0.1.3"
serde = { version = "1.0.164", features = ["derive"] }
